apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sysbox.fullname" . }}-label-node-rb
  labels:
  {{- include "sysbox.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "sysbox.fullname" . }}-node-labeler'
subjects:
- kind: ServiceAccount
  name: '{{ include "sysbox.fullname" . }}-label-node'
  namespace: '{{ .Release.Namespace }}'