apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ include "sysbox.fullname" . }}-runc
  labels:
  {{- include "sysbox.labels" . | nindent 4 }}
handler: sysbox-runc
scheduling:
  nodeSelector:
    sysbox-runtime: running