apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sysbox.fullname" . }}-label-node
  labels:
  {{- include "sysbox.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.labelNode.serviceAccount.annotations | nindent 4 }}